### Created by Dr. Benjamin Richards

### Download base image from repo
FROM tooldaq/core

### Run the following commands as super user (root):
USER root
ENV LD_LIBRARY_PATH=/opt/ToolFrameworkCore/lib/:/opt/ToolDAQFramework/lib/:/opt/boost_1_66_0/install/lib/:/opt/zeromq-4.0.7/lib/:$LD_LIBRARY_PATH

### Open terminal
CMD ["/opt/ToolDAQFramework/RemoteControl"]